project_id = "anponqqhjugwflakydsf"

[functions.generate-post]
verify_jwt = false

[functions.generate-dm]
verify_jwt = false

[functions.verify-url]
verify_jwt = false

[functions.sync-classroom]
verify_jwt = false
