// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-members.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-members.ts
var toMemberJson = (m) => ({
  id: String(m.id ?? ""),
  name: m.skool_name ?? null,
  username: m.skool_username ?? null,
  email: m.email ?? null,
  join_date: m.join_date ?? null,
  last_active: m.last_active ?? null,
  engagement_status: m.engagement_status ?? null,
  intent_tier: m.intent_tier ?? null,
  communities: Array.isArray(m.communities) ? m.communities.map(String) : [],
  segments: Array.isArray(m.segments) ? m.segments.map(String) : [],
  outreach_sent: Boolean(m.outreach_sent)
});
var list_members_default = defineTool({
  name: "list_members",
  title: "List members",
  description: "List community members with optional filters for community slug, engagement status, intent tier, or whether outreach was already sent.",
  inputSchema: {
    community: z.string().optional().describe("Community slug, e.g. crust-crumb-academy or from-oven-to-market."),
    engagement_status: z.string().optional().describe("Engagement status filter, e.g. active, inactive."),
    intent_tier: z.string().optional().describe("Intent tier filter, e.g. prospect."),
    outreach_sent: z.boolean().optional().describe("Filter on whether outreach has already been sent."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ community, engagement_status, intent_tier, outreach_sent, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("members").select(
      "id, skool_name, skool_username, email, join_date, last_active, engagement_status, intent_tier, communities, segments, outreach_sent"
    ).order("join_date", { ascending: false }).limit(limit ?? 25);
    if (community) query = query.contains("communities", [community]);
    if (engagement_status) query = query.eq("engagement_status", engagement_status);
    if (intent_tier) query = query.eq("intent_tier", intent_tier);
    if (outreach_sent !== void 0) query = query.eq("outreach_sent", outreach_sent);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const members = (data ?? []).map(toMemberJson);
    return {
      content: [{ type: "text", text: JSON.stringify(members, null, 2) }],
      structuredContent: { members, count: members.length }
    };
  }
});

// src/lib/mcp/tools/search-members.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var search_members_default = defineTool2({
  name: "search_members",
  title: "Search members",
  description: "Search members by name, Skool username, or email.",
  inputSchema: {
    query: z2.string().trim().min(2).describe("Text to match against name, username, or email."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max rows to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const safe = query.replace(/[%,]/g, " ").trim();
    const { data, error } = await supabase.from("members").select("id, skool_name, skool_username, email, engagement_status, communities").or(`skool_name.ilike.%${safe}%,skool_username.ilike.%${safe}%,email.ilike.%${safe}%`).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const results = (data ?? []).map((m) => ({
      id: String(m.id),
      name: m.skool_name ?? null,
      username: m.skool_username ?? null,
      email: m.email ?? null,
      engagement_status: m.engagement_status ?? null,
      communities: Array.isArray(m.communities) ? m.communities.map(String) : []
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results, count: results.length }
    };
  }
});

// src/lib/mcp/tools/get-member-compass.ts
import { defineTool as defineTool3, ToolError } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var get_member_compass_default = defineTool3({
  name: "get_member_compass",
  title: "Get member profile and compass",
  description: "Get one member's record plus their Member Compass insights (baking stage, struggles, goals, next best action).",
  inputSchema: {
    member_id: z3.string().uuid().optional().describe("Member id."),
    email: z3.string().trim().optional().describe("Member email."),
    username: z3.string().trim().optional().describe("Skool username.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ member_id, email, username }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!member_id && !email && !username) {
      throw new ToolError("Provide member_id, email, or username.");
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("members").select("*").limit(1);
    if (member_id) query = query.eq("id", member_id);
    else if (email) query = query.ilike("email", email);
    else if (username) query = query.ilike("skool_username", username);
    const { data, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) throw new ToolError("No member matched that lookup.");
    const { data: compass } = await supabase.from("member_compass_profiles").select(
      "baking_stage, struggles, learning_goals, bread_interests, why_they_bake, personal_hooks, next_best_action, recommended_resource_title, recommended_resource_url, insight_confidence, last_analyzed_at"
    ).eq("member_id", data.id).maybeSingle();
    const member = {
      id: String(data.id),
      name: data.skool_name ?? null,
      username: data.skool_username ?? null,
      email: data.email ?? null,
      join_date: data.join_date ?? null,
      last_active: data.last_active ?? null,
      engagement_status: data.engagement_status ?? null,
      intent_tier: data.intent_tier ?? null,
      nurture_status: data.nurture_status ?? null,
      notes: data.notes ?? null,
      communities: Array.isArray(data.communities) ? data.communities.map(String) : [],
      segments: Array.isArray(data.segments) ? data.segments.map(String) : []
    };
    const compassJson = compass ? {
      baking_stage: compass.baking_stage ?? null,
      struggles: Array.isArray(compass.struggles) ? compass.struggles.map(String) : [],
      learning_goals: Array.isArray(compass.learning_goals) ? compass.learning_goals.map(String) : [],
      bread_interests: Array.isArray(compass.bread_interests) ? compass.bread_interests.map(String) : [],
      why_they_bake: compass.why_they_bake ?? null,
      personal_hooks: Array.isArray(compass.personal_hooks) ? compass.personal_hooks.map(String) : [],
      next_best_action: compass.next_best_action ?? null,
      recommended_resource_title: compass.recommended_resource_title ?? null,
      recommended_resource_url: compass.recommended_resource_url ?? null,
      insight_confidence: compass.insight_confidence ?? null,
      last_analyzed_at: compass.last_analyzed_at ?? null
    } : null;
    return {
      content: [{ type: "text", text: JSON.stringify({ member, compass: compassJson }, null, 2) }],
      structuredContent: { member, compass: compassJson }
    };
  }
});

// src/lib/mcp/tools/list-outreach-templates.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z4 } from "npm:zod@^3.25.76";
var list_outreach_templates_default = defineTool4({
  name: "list_outreach_templates",
  title: "List outreach templates",
  description: "List the saved DM and email outreach templates, with their body text and merge tags.",
  inputSchema: {
    channel: z4.string().optional().describe("Filter by channel, e.g. dm or email."),
    active_only: z4.boolean().optional().describe("Only return active templates (default true).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ channel, active_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("outreach_templates").select("id, key, name, description, channel, segment_key, subject, body, merge_tags, is_active").order("name");
    if (channel) query = query.eq("channel", channel);
    if (active_only !== false) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const templates = (data ?? []).map((t) => ({
      id: String(t.id),
      key: t.key ?? null,
      name: t.name ?? null,
      description: t.description ?? null,
      channel: t.channel ?? null,
      segment_key: t.segment_key ?? null,
      subject: t.subject ?? null,
      body: t.body ?? null,
      merge_tags: Array.isArray(t.merge_tags) ? t.merge_tags.map(String) : [],
      is_active: Boolean(t.is_active)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(templates, null, 2) }],
      structuredContent: { templates, count: templates.length }
    };
  }
});

// src/lib/mcp/tools/community-overview.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@3.0.4";
var COMMUNITIES = ["crust-crumb-academy", "from-oven-to-market"];
var community_overview_default = defineTool5({
  name: "community_overview",
  title: "Community overview",
  description: "Summary counts of the member base: total members, members per community, and how many still need outreach.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const head = { count: "exact", head: true };
    const [total, needsOutreach, compassAnalyzed, ...perCommunity] = await Promise.all([
      supabase.from("members").select("id", head),
      supabase.from("members").select("id", head).eq("outreach_sent", false),
      supabase.from("member_compass_profiles").select("id", head),
      ...COMMUNITIES.map(
        (slug) => supabase.from("members").select("id", head).contains("communities", [slug])
      )
    ]);
    const firstError = [total, needsOutreach, compassAnalyzed, ...perCommunity].find((r) => r.error);
    if (firstError?.error) {
      return { content: [{ type: "text", text: firstError.error.message }], isError: true };
    }
    const overview = {
      total_members: total.count ?? 0,
      needs_outreach: needsOutreach.count ?? 0,
      compass_profiles: compassAnalyzed.count ?? 0,
      communities: COMMUNITIES.map((slug, i) => ({ slug, members: perCommunity[i].count ?? 0 }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(overview, null, 2) }],
      structuredContent: { overview }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "anponqqhjugwflakydsf";
var mcp_default = defineMcp({
  name: "crust-crumb-companion",
  title: "Crust & Crumb Companion",
  version: "0.1.0",
  instructions: "Read-only tools for the Crust & Crumb Companion community console. Use community_overview for headline counts, list_members and search_members to find people, get_member_compass for one member's profile and coaching insights, and list_outreach_templates for saved DM and email copy. Nothing here sends messages.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    community_overview_default,
    list_members_default,
    search_members_default,
    get_member_compass_default,
    list_outreach_templates_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
